#!/bin/bash


# create app

startapp() {
    docker compose -f local.yml exec web python -m manage startapp $@
}


# migration
migrations() {
    docker compose -f local.yml exec web python -m manage makemigrations $@
}

migrate() {
    docker compose -f local.yml exec web python -m manage migrate
}

migration-plan() {
    docker compose -f local.yml exec web python -m manage showmigrations --plan 
}

web() {
    docker-compose -f local.yml exec web $@
}

# Lint

lint:ci() {
    SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure
}

lint() {
    git add .; poetry run pre-commit run --all-files 
}

update-precommit() {
    poetry run pre-commit uninstall; poetry run pre-commit clean; poetry run pre-commit install
}


# contrainer
up() {
    docker-compose -f local.yml up $@ --build -d 
}

down() {
    docker-compose -f local.yml down $@
}

prod-up() {
    docker-compose -f prod.yml up --build -d 
}

prod-down() {
    docker-compose -f prod.yml down
}

# Tests
test() {
    docker-compose -f local.yml exec -e IN_TEST=1 web pytest $@ 
}


test-dist() {
    docker-compose -f local.yml exec -e IN_TEST=1 web pytest $@ \
    -n auto \
    --dist loadfile
}

test-report() {
    docker-compose -f local.yml exec -e IN_TEST=1 web pytest $@  \
    -n auto \
    --dist loadfile \
    --cov-report term-missing \
    --cov-report html \
    --cov=core \
    --cov-config=pyproject.toml
}


# CI
test:ci() {
    poetry run env IN_TEST=1 pytest \
    -x \
    -n auto \
    --dist loadfile
}



help() {
    echo "${1} <task> <arg>s"
    echo "Tasks:"
    compgen -A function | cat -n 
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
