# Generated by Django 5.2.1 on 2025-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_options_remove_post_title_postmedia_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmedia",
            options={},
        ),
        migrations.AddConstraint(
            model_name="postmedia",
            constraint=models.UniqueConstraint(
                fields=("post", "order"), name="Unique order per post."
            ),
        ),
    ]
