# Generated by Django 5.2.1 on 2025-06-11 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_postmedia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
    ]
