# Generated by Django 5.2.1 on 2025-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
    ]
