# Generated by Django 5.2.1 on 2025-06-18 08:33

from django.db import migrations


def populate_media_user(apps, scheme_editor):
    PostMedia = apps.get_model("posts", "PostMedia")

    for media in PostMedia.objects.all():
        media.user = media.post.user
        media.save()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_postmedia_user_album"),
    ]

    operations = [migrations.RunPython(populate_media_user)]
