# Generated by Django 5.2.1 on 2025-06-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_populate_post_media_user"),
        ("profiles", "0003_alter_profile_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="user",
        ),
        migrations.RemoveField(
            model_name="postmedia",
            name="user",
        ),
        migrations.AddField(
            model_name="album",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="postmedia",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="profiles.profile",
            ),
        ),
    ]
