# Generated by Django 5.2.1 on 2025-06-18 08:53

from django.db import migrations


def populate_media_profile(apps, scheme_editor):
    PostMedia = apps.get_model("posts", "PostMedia")

    for media in PostMedia.objects.all():
        media.profile = media.post.user.profile
        media.save()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_remove_album_user_remove_postmedia_user_and_more"),
    ]

    operations = [migrations.RunPython(populate_media_profile)]
