# Generated by Django 5.2.1 on 2025-06-22 17:19

import functools
import uuid

import django.db.models.deletion
from django.db import migrations, models

import network.tools.media


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_album_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmedia",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="album",
            name="photos",
        ),
        migrations.CreateModel(
            name="AlbumMedia",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(
                            network.tools.media.generate_file_path,
                            *(),
                            path_prefix="posts",
                        ),
                    ),
                ),
                ("order", models.SmallIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="posts.album",
                    ),
                ),
            ],
        ),
    ]
