# Generated by Django 5.2.1 on 2025-06-25 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_alter_postmedia_options_remove_album_photos_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="AlbumMedia",
        ),
    ]
