# Generated by Django 5.2.1 on 2025-06-28 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_remove_albummedia_album_delete_album_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postlike",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
