# Generated by Django 5.2.1 on 2025-06-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_alter_postlike_options_remove_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
