# Generated by Django 5.2.1 on 2025-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_post_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
