# Generated by Django 5.2.1 on 2025-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_post_publish_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
