# Generated by Django 5.2.1 on 2025-08-04 09:08

import functools

from django.db import migrations, models

import network.tools.media


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_post_celery_task_id_post_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="born_from_egg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    network.tools.media.generate_file_path, *(), path_prefix="posts"
                ),
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="born_from_egg_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    network.tools.media.generate_file_path,
                    *(),
                    path_prefix="posts/thumbnails",
                ),
            ),
        ),
    ]
