# Generated by Django 5.2.1 on 2025-08-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_post_born_from_egg_post_born_from_egg_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="born_from_egg_thumbnail",
        ),
        migrations.AlterField(
            model_name="post",
            name="born_from_egg",
            field=models.CharField(
                blank=True,
                help_text="Static path like 'media/images/egg.png'",
                max_length=255,
            ),
        ),
    ]
