# Generated by Django 5.2.1 on 2025-08-14 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_remove_post_born_from_egg_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmedia",
            options={"ordering": ["order"]},
        ),
    ]
