# Generated by Django 5.2.1 on 2025-08-15 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_alter_postmedia_options"),
        ("profiles", "0017_remove_regularegg_user_remove_specialegg_user_egg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="born_from_egg",
        ),
        migrations.AddField(
            model_name="post",
            name="egg",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="born_from_egg",
                to="profiles.egg",
            ),
            preserve_default=False,
        ),
    ]
