# Generated by Django 5.2.1 on 2025-08-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0021_remove_post_born_from_egg_post_egg"),
        ("profiles", "0017_remove_regularegg_user_remove_specialegg_user_egg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="egg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts",
                to="profiles.egg",
            ),
        ),
    ]
