# Generated by Django 5.2.1 on 2025-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0022_alter_post_egg"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
