# Generated by Django 5.2.1 on 2025-09-20 17:22

from django.db import migrations


def populate_post_comment_count(apps, scheme_editor):
    Post = apps.get_model("posts", "Post")
    qs = Post.objects.all()

    for post in qs:
        post.comment_count = post.comments.count()
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_post_comment_count"),
    ]

    operations = [migrations.RunPython(populate_post_comment_count)]
