# Generated by Django 5.2.1 on 2026-01-19 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0024_populate_comment_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comment_count",
        ),
    ]
