# Generated by Django 5.2.1 on 2025-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activity_status",
            field=models.CharField(
                choices=[
                    ("swimming", "Swimming"),
                    ("resting", "Resting"),
                    ("exploring", "Exploring"),
                    ("sunbathing", "Sunbathing"),
                    ("hiding_in_shell", "Hiding in Shell"),
                ],
                default="exploring",
                max_length=20,
            ),
        ),
    ]
