# Generated by Django 5.2.1 on 2025-07-21 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_profile_last_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="activity_status",
        ),
    ]
