# Generated by Django 5.2.1 on 2025-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_remove_profile_activity_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_seen",
        ),
    ]
