# Generated by Django 5.2.1 on 2025-08-05 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_remove_profile_last_seen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularEgg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ceal", "Ceal"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialEgg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("volcano", "Volcano"),
                            ("rainbow", "Rainbow"),
                            ("devil", "Devil"),
                            ("angel", "Angel"),
                            ("skull", "Skull"),
                            ("swamp", "Swamp"),
                            ("golden", "Golden"),
                            ("silver", "Silver"),
                            ("thunder", "Thunder"),
                            ("bubble", "Bubble"),
                            ("lucky", "Lucky"),
                            ("candy", "Candy"),
                            ("star", "Star"),
                            ("sakura", "Sakura"),
                            ("cyber", "Cyber"),
                            ("universe", "Universe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
