# Generated by Django 5.2.1 on 2025-08-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_regularegg_specialegg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regularegg",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="regularegg",
            name="url",
        ),
        migrations.AlterField(
            model_name="specialegg",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
