# Generated by Django 5.2.1 on 2025-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_remove_regularegg_quantity_remove_regularegg_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularegg",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="regularegg",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
