# Generated by Django 5.2.1 on 2025-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_regularegg_quantity_regularegg_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularegg",
            name="url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="specialegg",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
