# Generated by Django 5.2.1 on 2025-08-07 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alter_regularegg_url_alter_specialegg_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialegg",
            name="user",
        ),
        migrations.DeleteModel(
            name="RegularEgg",
        ),
        migrations.DeleteModel(
            name="SpecialEgg",
        ),
    ]
