# Generated by Django 5.2.1 on 2025-08-07 06:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_remove_specialegg_user_delete_regularegg_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularEgg",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ceal", "Ceal"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialEgg",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("volcano", "Volcano"),
                            ("rainbow", "Rainbow"),
                            ("devil", "Devil"),
                            ("angel", "Angel"),
                            ("skull", "Skull"),
                            ("swamp", "Swamp"),
                            ("golden", "Golden"),
                            ("silver", "Silver"),
                            ("thunder", "Thunder"),
                            ("bubble", "Bubble"),
                            ("lucky", "Lucky"),
                            ("candy", "Candy"),
                            ("star", "Star"),
                            ("sakura", "Sakura"),
                            ("cyber", "Cyber"),
                            ("universe", "Universe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
