# Generated by Django 5.2.1 on 2025-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_regularegg_specialegg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularegg",
            name="name",
            field=models.CharField(
                choices=[
                    ("teal", "Teal"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                ],
                max_length=20,
            ),
        ),
    ]
