# Generated by Django 5.2.1 on 2025-08-15 02:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_alter_regularegg_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularegg",
            name="name",
            field=models.CharField(
                choices=[
                    ("teal", "Teal"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("chiken", "Chicken"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="specialegg",
            name="name",
            field=models.CharField(
                choices=[
                    ("volcano", "Volcano"),
                    ("rainbow", "Rainbow"),
                    ("devil", "Devil"),
                    ("angel", "Angel"),
                    ("skull", "Skull"),
                    ("swamp", "Swamp"),
                    ("golden", "Golden"),
                    ("silver", "Silver"),
                    ("thunder", "Thunder"),
                    ("bubble", "Bubble"),
                    ("lucky", "Lucky"),
                    ("candy", "Candy"),
                    ("star", "Star"),
                    ("sakura", "Sakura"),
                    ("cyber", "Cyber"),
                    ("universe", "Universe"),
                    ("rubik's cube", "Rubik's Cube"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EasterEgg",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("glichy", "Glichy"),
                            ("buggy", "Buggy"),
                            ("easter", "Easter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="easter_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
