# Generated by Django 5.2.1 on 2025-08-15 06:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_alter_regularegg_name_alter_specialegg_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regularegg",
            name="user",
        ),
        migrations.RemoveField(
            model_name="specialegg",
            name="user",
        ),
        migrations.CreateModel(
            name="Egg",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=20)),
                (
                    "egg_type",
                    models.CharField(
                        choices=[
                            ("special", "Special"),
                            ("regular", "Regular"),
                            ("easter", "Easter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_eggs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="EasterEgg",
        ),
        migrations.DeleteModel(
            name="RegularEgg",
        ),
        migrations.DeleteModel(
            name="SpecialEgg",
        ),
    ]
