# Generated by Django 5.2.1 on 2025-08-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_remove_regularegg_user_remove_specialegg_user_egg_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eggs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
