# Generated by Django 5.2.1 on 2025-05-27 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
