# Generated by Django 5.2.1 on 2025-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
