# Generated by Django 5.2.1 on 2025-06-01 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_profile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
