# Generated by Django 5.2.1 on 2025-07-22 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
